name: bookrabbit
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+7

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.5
  encrypted_shared_preferences:
  logger:
  intl:
  kakao_flutter_sdk: ^1.2.0 # 전체 추가
  sign_in_with_apple: ^4.1.0
  dio: ^4.0.0
  carousel_slider: ^4.0.0
  flutter_native_splash:
  cached_network_image: ^3.2.1
  lazy_load_scrollview:
  iamport_flutter: ^0.10.0
  package_info_plus:
  url_launcher:
  like_button: ^2.0.4
  fluttertoast:
  webview_flutter:
  font_awesome_flutter:
  json_annotation:

  # image
  image_cropper: ^3.0.0
  image_picker: ^0.8.2
  path_provider: ^2.0.2
  flutter_image_compress: ^1.0.0
  firebase_storage: ^10.0.1

  # analytics
  firebase_core:
  firebase_analytics:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.1+1
  firebase_dynamic_links: ^4.3.9
  share_plus: ^4.4.0
  uni_links: ^0.5.1

  # socket
  web_socket_channel:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  build_runner:
  json_serializable:
  import_sorter: ^4.6.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/loading/
    - assets/images/persons/
    - assets/images/groups/
    - assets/icon/bottom_navbar/
    - assets/icon/login/
    - assets/icon/common/
    - assets/icon/my_page/
    - assets/icon/sns/
    - assets/splash_4x.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
