const DEFAULT_PAGE_SIZE = 3;

const PROFILE_THUMBNAIL_LOGO_SIZE = 20.0;
const COMMON_PADDING = 16.0;
const COMMON_VERTICAL_PADDING = 20.0;

const RESOURCE_CARD_HEIGHT_WIDTH_ASPECT_RATIO = 1 / 2;
const CLUB_CARD_HEIGHT_WIDTH_ASPECT_RATIO = 9 / 10;
const PRODUCT_CARD_HEIGHT_WIDTH_ASPECT_RATIO = 3 / 1;
